export interface TruthOrDareQuestion {
  type: 'truth' | 'dare';
  text: string;
}

export interface WouldYouRatherQuestion {
  optionA: string;
  optionB: string;
}

export interface GameCategory {
  id: string;
  title: string;
  icon: string;
  color: string;
  description: string;
  stats: string;
  subtitle: string;
  questions: (string | TruthOrDareQuestion | WouldYouRatherQuestion)[];
}

export const gameData: Record<string, GameCategory> = {
  intimateQuestions: {
    id: 'intimateQuestions',
    title: 'Intimate Questions',
    icon: 'heart',
    color: 'from-rose-400 to-pink-500',
    description: 'Deep questions to discover each other\'s hearts and minds',
    stats: 'Soul Connection',
    subtitle: 'Connect Deeply',
    questions: [
      "What was your first impression of me, and how has it changed?",
      "What's a dream you've never told me about?",
      "When do you feel most loved by me?",
      "What's something about your past that shaped who you are today?",
      "What's your biggest fear about our future together?",
      "What's one thing you'd like us to experience together that we haven't yet?",
      "How do you want to be comforted when you're feeling down?",
      "What's a childhood memory that still makes you smile?",
      "What's something you admire about the way I handle challenges?",
      "If we could travel anywhere together, where would you choose and why?",
      "What's your deepest insecurity that you feel safe sharing with me?",
      "How has being with me changed your perspective on love?",
      "What's something you've never told anyone else but want to share with me?",
      "What does emotional intimacy mean to you?",
      "When do you feel most vulnerable, and how can I support you?",
      "What's a fantasy or aspiration you have for us as a couple?",
      "How do you want to grow as a person within our relationship?",
      "What's something about yourself you're still discovering?",
      "What's your love language, and how do you want me to express love?",
      "What makes you feel most beautiful/handsome in my eyes?"
    ]
  },
  romanticDares: {
    id: 'romanticDares',
    title: 'Romantic Dares',
    icon: 'kiss',
    color: 'from-red-400 to-rose-500',
    description: 'Sweet and playful challenges to bring you closer',
    stats: 'Passion & Play',
    subtitle: 'Be Playful',
    questions: [
      "Give your partner a 30-second massage on their shoulders",
      "Write 'I love you' on your partner's back with your finger and have them guess",
      "Share three things you're grateful for about your partner",
      "Dance together to an imaginary slow song for one minute",
      "Give your partner five genuine compliments",
      "Feed your partner a small treat or snack",
      "Tell your partner about your favorite memory with them",
      "Give your partner a gentle kiss on their forehead",
      "Hold hands and maintain eye contact for 30 seconds without talking",
      "Tell your partner why you're proud to be with them",
      "Give your partner a sensual hand massage with lotion",
      "Whisper something seductive in your partner's ear",
      "Kiss your partner's neck softly and slowly",
      "Undress your partner with only your eyes for 30 seconds",
      "Give your partner a full-body massage with oils",
      "Take turns describing what you want to do to each other later",
      "Kiss every inch of your partner's face except their lips",
      "Tell your partner your favorite thing about their body",
      "Create a romantic atmosphere and slow dance intimately",
      "Feed each other chocolate or strawberries sensually"
    ]
  },
  relationshipChoices: {
    id: 'relationshipChoices',
    title: 'Relationship Choices',
    icon: 'balance-scale',
    color: 'from-purple-400 to-indigo-500',
    description: 'Explore preferences and discover what matters most to both of you',
    stats: 'Tough Choices',
    subtitle: 'Choose Together',
    questions: [
      { optionA: "Plan every detail of our dates", optionB: "Be completely spontaneous" },
      { optionA: "Spend a quiet evening at home", optionB: "Go out for an adventure" },
      { optionA: "Receive love through words", optionB: "Receive love through actions" },
      { optionA: "Travel the world together", optionB: "Build a beautiful home together" },
      { optionA: "Have deep conversations every day", optionB: "Enjoy comfortable silence together" },
      { optionA: "Be able to read each other's minds", optionB: "Always surprise each other" },
      { optionA: "Celebrate anniversaries grandly", optionB: "Appreciate small daily moments" },
      { optionA: "Share all the same interests", optionB: "Have different hobbies to share" },
      { optionA: "Know everything about each other's past", optionB: "Focus only on our future together" },
      { optionA: "Express love through gifts", optionB: "Express love through quality time" }
    ]
  },
  memoryLane: {
    id: 'memoryLane',
    title: 'Memory Lane',
    icon: 'photo',
    color: 'from-amber-400 to-orange-500',
    description: 'Reminisce about your journey together and share precious memories',
    stats: 'Cherished Moments',
    subtitle: 'Remember Together',
    questions: [
      "What's your favorite memory from our first month together?",
      "Describe the moment you knew you had deep feelings for me",
      "What's the funniest thing that's happened to us as a couple?",
      "What's a challenge we've overcome together that made us stronger?",
      "What's your favorite photo of us and why?",
      "What's something I did early in our relationship that impressed you?",
      "What's a tradition we've created together that you love?",
      "What's your favorite way we've celebrated together?",
      "What's a song, movie, or place that always reminds you of us?",
      "What's something about our relationship that makes you feel proud?"
    ]
  },
  dreamsTogether: {
    id: 'dreamsTogether',
    title: 'Dreams Together',
    icon: 'star',
    color: 'from-violet-400 to-purple-500',
    description: 'Share your hopes, dreams, and visions for your future together',
    stats: 'Future Visions',
    subtitle: 'Dream Big',
    questions: [
      "What's one goal you'd like us to achieve together in the next year?",
      "How do you envision our perfect weekend together?",
      "What's a new tradition you'd like to start with me?",
      "Where do you see us in five years?",
      "What's an adventure you'd love for us to embark on together?",
      "What's something new you'd like to learn or try with me?",
      "How would you like us to celebrate our next milestone?",
      "What's a way you'd like us to give back to others together?",
      "What's your ideal way to spend a holiday with me?",
      "What's a dream date you'd love to plan for us?"
    ]
  },
  lovingTouch: {
    id: 'lovingTouch',
    title: 'Loving Touch',
    icon: 'hand-heart',
    color: 'from-pink-400 to-rose-500',
    description: 'Gentle, affectionate gestures to show your love and care',
    stats: 'Physical Connection',
    subtitle: 'Show Love',
    questions: [
      "Hold your partner's hand and trace their palm gently",
      "Give your partner a warm, lingering hug",
      "Brush a strand of hair away from your partner's face",
      "Give your partner a gentle back rub for two minutes",
      "Kiss your partner's hand like royalty",
      "Put your arm around your partner and pull them close",
      "Give your partner butterfly kisses with your eyelashes on their cheek",
      "Massage your partner's temples gently",
      "Hold your partner close and sway together slowly",
      "Trace 'I love you' on your partner's arm with your finger",
      "Caress your partner's face while looking into their eyes",
      "Run your fingers through your partner's hair slowly",
      "Kiss your partner's shoulders and collarbone gently",
      "Hold your partner from behind and breathe together",
      "Massage your partner's feet while they relax",
      "Touch your partner's body like you're memorizing every curve",
      "Give your partner goosebumps by lightly tracing their skin",
      "Intertwine your fingers and hold hands for five minutes",
      "Place your hand on your partner's heart and feel it beat",
      "Cuddle naked and just enjoy the skin-to-skin contact"
    ]
  },
  spicyQuestions: {
    id: 'spicyQuestions',
    title: 'Spicy Questions',
    icon: 'flame',
    color: 'from-red-500 to-orange-500',
    description: 'Intimate questions to explore desires and deepen passion',
    stats: 'Adults Only',
    subtitle: 'Get Heated',
    questions: [
      "What's your favorite part of my body and why?",
      "What's something you've always wanted to try with me?",
      "Describe your perfect romantic evening with me",
      "What turns you on most about me?",
      "What's your biggest fantasy involving us?",
      "Where's the most adventurous place you'd want to be intimate?",
      "What's something new you'd like to explore together?",
      "How do you like to be kissed?",
      "What's your favorite way for me to touch you?",
      "Describe the most passionate moment we've shared",
      "What drives you wild when I do it?",
      "What's something that instantly makes you think of me?",
      "How do you want me to seduce you?",
      "What's your favorite memory of us being intimate?",
      "What's something you find irresistibly attractive about me?",
      "Describe your ideal morning after spending the night together",
      "What's a secret desire you have about our relationship?",
      "How do you want to surprise me romantically?",
      "What makes you feel most desired by me?",
      "What's something you want more of in our physical relationship?"
    ]
  },
  seductionDares: {
    id: 'seductionDares',
    title: 'Seduction Dares',
    icon: 'fire',
    color: 'from-purple-500 to-red-500',
    description: 'Playful challenges to ignite passion and desire',
    stats: 'Heat Level: Hot',
    subtitle: 'Turn Up Heat',
    questions: [
      "Give your partner a seductive look for 30 seconds without breaking eye contact",
      "Whisper your partner's name in their ear in the most seductive way possible",
      "Kiss your partner's neck for one minute",
      "Tell your partner exactly what you want to do to them tonight",
      "Give your partner a lap dance to an imaginary song",
      "Remove one piece of your partner's clothing very slowly",
      "Massage your partner's inner thighs for two minutes",
      "Kiss your partner passionately for two minutes straight",
      "Tell your partner your favorite thing about making love to them",
      "Give your partner a hickey somewhere only you can see",
      "Describe in detail how you want your partner to touch you",
      "Blindfold your partner and kiss them somewhere unexpected",
      "Take a steamy shower or bath together",
      "Give your partner a full-body massage with oils",
      "Tell your partner your dirtiest fantasy about them",
      "Kiss your partner's body from head to toe",
      "Recreate your first kiss but make it more passionate",
      "Give your partner goosebumps using only your breath",
      "Tell your partner what you love most about their body",
      "Make your partner feel like the most desirable person alive",
      "Remove one piece of your clothing for every compliment your partner gives you.",
      "Let your partner blindfold you and kiss you wherever they want for 1 minute.",
      "Demonstrate your favorite position using pillows, then have your partner join you.",
      "Touch yourself the way you do when your partner isn't around while they watch.",
      "Let your partner place an ice cube anywhere on your body and trace it wherever they want.",
      "Role play meeting each other for the first time at a bar, but you can only communicate through touch.",
      "Let your partner tie your hands and tease you for 2 minutes without being able to touch back.",
      "Describe in detail what you want your partner to do to you tonight using at least 10 specific words.",
      "Take off your partner's underwear using only your teeth.",
      "Give your partner a sensual massage, hitting all their erogenous zones except the obvious ones.",
      "Act out your favorite sex scene from a movie.",
      "Take turns being dominant for 5 minutes each, showing exactly what you want.",
      "Play a game of strip rock, paper, scissors until someone is completely naked.",
      "Guide your partner's hands to show them exactly how you like to be touched in your most sensitive areas.",
      "Send your partner into another room, then text them three things you're going to do to them when they return.",
      "Start foreplay in an unusual place in your home.",
      "Give your partner pleasure while maintaining direct eye contact the entire time.",
      "Let your partner draw on your body with chocolate sauce, then lick it off.",
      "Make out in front of a mirror for 3 minutes, describing what you see and how it makes you feel.",
      "Let your partner spank you and honestly tell them if you want it harder, softer, or just right.",
      "Send your ex a message saying you miss them.",
      "Make eye contact with the person to your right and moan for 10 seconds.",
      "Ask a stranger for advice on a strange rash you’ve recently developed.",
      "Make your orgasm face the next stranger you see until they make eye contact with you.",
      "Seductively eat a banana whilst locking eyes with the person to your left.",
      "Send one of your parents a sext and don’t reply for one hour.",
      "Pass your phone to the person on your left and let them post a sexual status to your Facebook.",
      "Perform a seductive dance in front of the group.",
      "Pick up the nearest object to you and demonstrate how to put on protection.",
      "Close your eyes, pick a random phone contact and leave them a dirty voicemail.",
      "Drop an ice cube in your pants.",
      "Google the dirtiest thing you can think of and show it to the person next to you.",
      "FaceTime your most recent contact, burp, then hang up.",
      "Smell everyone’s armpits and rank them from best to worst.",
      "Tell us the one bedtime secret no one knows about you.",
      "Lick your partner’s ears.",
      "Spank, squeeze, and pinch your partner’s butt.",
      "Place an ice cube on the girl’s belly button until it melts. The guy can only use his lips to keep the cube in place or move it around. The guy can only use his lips to keep the cube in place or move it around *it’s a lot harder to keep the ice cube in place when it starts to melt or the girl starts to feel cold*.",
      "Pass a candy to your partner using just the lips / unwrap a candy together using only the lips.",
      "Kiss each other for a whole minute.",
      "Give your partner a lap dance.",
      "One partner lies down. The other partner moves their hand or a feather all over the laying partner’s body including all strategic regions.",
      "Unhook your girlfriend’s bra and take it off her body using just one hand.",
      "Lift your girlfriend’s shirt up from the back all the way to the collar using just your teeth.",
      "Stroke your partner’s tee shirt/pants until we see the pants move or the tee shirt stiffen.",
      "Eat a melting piece of chocolate off your girlfriend’s boobs *cleavage will do for the less horny ones*.",
      "Give your man a boner without touching his member.",
      "Suck all ten of your partner’s toes / Kiss your partner’s feet and legs",
      "Show everyone playing the game your favorite porn site",
      "Show everyone playing the game your craziest sex position",
      "Give your partner a hickey",
      "Teach everyone your kinkiest sex technique",
      "Recreate the sounds you make during sex",
      "Demonstrate how to give a blow job on an unpeeled banana",
      "Kiss and lick your partner’s feet for 2 minutes",
      "Bend your partner over your knee and spank them ten times",
      "Bend over your partner’s knee and let them spank you twenty times",
      "Slowly kiss your partner from their feet to the top of their head",
      "Grab your partner’s hair and pull them into your boobs/crotch",
      "Twerk for your partner/for the the group",
      "Swap clothes with your partner",
      "Race your partner to see who can cum the fastest",
      "Kiss your partner while also eating a candy",
      "Your partner has to use a sex toy on themselves the next time you have sex",
      "Go commando for 24 hours. (Commando = wear no underwear)",
      "Guys: Finger your girl, then taste it. Women: Taste his precum",
      "Drink a shot from your partner’s belly button",
      "Pass a candy/grape to your partner using only your lips",
      "Recreate the weirdest thing that ever happened to you during sex",
      "Try to turn your partner without touching them",
      "Give your partner anilingus",
      "Give your female partner oral sex while they sit at the computer/watch TV/play video games",
      "Eat fruit/food off your partner",
      "Undress your partner with everything but your hands",
      "Get yourself off by dry humping your partner",
      "Wear a butt plug for the entire day",
      "Try snowballing with your partner after a blow job",
      "Don’t masturbate for an entire month",
      "Strip for your partner",
      "Suck your partner’s nipples",
      "Guys: Spell the alphabet on your girl’s pussy with your tongue. Women: Spell the alphabet on the tip of your man’s penis with your tongue",
      "Rest your hands inside your partner’s pants for the next 5/10/20 minutes",
      "Sit on your partner’s face",
      "Lick whipped cream off your partner’s chest/breasts/pussy/penis",
      "Masturbate in front of the group/me",
      "With a blindfold on, try to identify everyone in the group by their genitals",
      "Stay naked for the next 2/5/10/30 minutes",
      "Make your partner cum using only your lips",
      "Take a shower and wash your partner",
      "Send your partner a naked snap",
      "Tell two people in the group to start kissing, then direct them to start doing other stuff like undressing, groping, etc",
      "Orgasm",
      "Send a naughty text to your partner."
    ]
  },
  naughtyChoices: {
    id: 'naughtyChoices',
    title: 'Naughty Choices',
    icon: 'devil',
    color: 'from-red-600 to-pink-600',
    description: 'Provocative choices to explore your wild side together',
    stats: 'Choose Wisely',
    subtitle: 'Be Bold',
    questions: [
      { optionA: "Seduce me with words", optionB: "Seduce me with touch" },
      { optionA: "Make love in the morning", optionB: "Make love at night" },
      { optionA: "Be the dominant one tonight", optionB: "Let me take control" },
      { optionA: "Slow and romantic", optionB: "Passionate and intense" },
      { optionA: "Role play as strangers", optionB: "Be completely ourselves" },
      { optionA: "Make out in public", optionB: "Keep it private" },
      { optionA: "Surprise me spontaneously", optionB: "Plan something elaborate" },
      { optionA: "Lights on", optionB: "Candlelight only" },
      { optionA: "Talk during intimacy", optionB: "Express with sounds only" },
      { optionA: "Focus on foreplay", optionB: "Skip to the main event" },
      { optionA: "Try something completely new", optionB: "Perfect what we love" },
      { optionA: "Wake me up with kisses", optionB: "Let me sleep in your arms" },
      { optionA: "Shower together", optionB: "Massage with oils" },
      { optionA: "Weekend getaway", optionB: "Romantic night at home" },
      { optionA: "Express love physically", optionB: "Express love verbally" }
    ]
  }
};
